---
- name: Download Kubernetes {{kubernetes_version}}
  get_url:
    url: http://storage.googleapis.com/kubernetes-release/release/v{{kubernetes_version}}/bin/linux/amd64/kubectl
    dest: /tmp/

- name: Copy kubectl {{kubernetes_version}} to /usr/bin/
  become: true
  copy:
    src: /tmp/kubectl
    dest: /usr/bin/kubectl
    force: yes

- name: Add executable mode to kubectl
  become: true
  become_user: root
  file:
    path: /usr/bin/kubectl
    mode: 0775

- name: Download Minikube {{minikube_version}}
  get_url:
    url: https://storage.googleapis.com/minikube/releases/v{{minikube_version}}/minikube-linux-amd64
    dest: /tmp/

- name: Copy minikube {{kubernetes_version}} to /usr/local/bin/
  become: true
  copy:
    src: /tmp/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    force: yes

- name: Add executable mode to minikube
  become: true
  become_user: root
  file:
    path: /usr/local/bin/minikube
    mode: 0775
