---
- name: Download NodeJS {{node_version}}
  get_url:
    url: http://nodejs.org/dist/v{{node_version}}/node-v{{node_version}}-linux-x64.tar.gz
    dest: /tmp/

- name: Install NodeJS {{node_version}}
  become: true
  unarchive:
    src: /tmp/node-v{{node_version}}-linux-x64.tar.gz
    dest: /usr/local/
    extra_opts: "--strip-components=1"

- name: Configure npm global location
  shell: npm config set prefix $HOME\/.npm-global/
