---
- name: Install tilix
  become: true
  apt:
    name: tilix
    state: present

- name: Create symlink for vte.sh
  become: true
  file:
    src: /etc/profile.d/vte-2.91.sh
    dest: /etc/profile.d/vte.sh
    state: link
